# TO CREATE A SPECIFIC BASE IMAGE - FROM
FROM node:12

# ADD CURRENT WORKING DIRECTORY
WORKDIR /app

# TO COPY DEPENDENCIES FIRST IN THE CONTAINER. DOCKER USUALLY CACHES INSTEAD OF INSTALLING EVERYTHING EVERYTIME WE BUILD IT
COPY package*.json ./

# IT WILL SIMPLY INSTALL THE ABOVE DEPENDENCIES
RUN npm install

# COPY ALL OUR LOCAL FILES TO THE CURRENT WORKING DIRECTORY IN THE CONTAINER
COPY . .

# SET THE ENVIRONMENT VARIABLE INSIDE A CONTAINER
ENV PORT=7676

# TO ACCESS THE NODE JS EXPRESS APP PUBLICLY, OR TO LISTEN AT THE PORT WE EXPOSE THAT PORT FROM INSIDE THE CONTAINER
EXPOSE 7676

# TO TELL THE CONTAINER HOW TO RUN THE EXPRESS APP
CMD ["npm", "start"]


